In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

Mounted at /content/drive

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Dataset/Assignment 1/car.csv')
df.head()

   User ID  Gender   Age  AnnualSalary  Purchased
0        1     0.0  32.0      100000.0          1
1        2     1.0  38.0       63500.0          0
2        3     0.0  20.0           NaN          0
3        4     1.0  48.0      119000.0          1
4        5     0.0  41.0      108500.0          1

In [3]:
# NULL Values
df.isnull().sum()

User ID           0
Gender           16
Age              93
AnnualSalary    118
Purchased         0
dtype: int64

In [4]:
# Null Values only in AnnualSalary
df['AnnualSalary'].isnull().sum()

np.int64(118)

In [8]:
#Dropping rows which have atleast one null value in any field
df.dropna(how='any', inplace=True)
print(df.shape)

(776, 5)

In [9]:
# Task 5-Dropping the rows which have null values in all the fields
df.dropna(how='all', inplace=True)
print(df.shape)

(776, 5)

In [10]:
# Task 6- Dropping the columns where there are null value in any record
df.dropna(axis=1, how='any', inplace=True)
print(df.columns)

Index(['User ID', 'Gender', 'Age', 'AnnualSalary', 'Purchased'], dtype='object')

In [11]:
# Task 7 - Dropping columns where there are null values in all records
df.dropna(axis=1, how='all', inplace=True)
print(df.columns)

Index(['User ID', 'Gender', 'Age', 'AnnualSalary', 'Purchased'], dtype='object')

In [12]:
#Task 8- Creating copy of dataset and replacing the null values in AnnualSalary with 70000
df_copy = df.copy()
df_copy['AnnualSalary'] = df_copy['AnnualSalary'].fillna(70000)

In [13]:
#Task 9- Replace the null values in Age with 0
df['Age'] = df['Age'].fillna(0)

In [14]:
#Task 10- Replace the null values in AnnualSalary with mean of the values
df['AnnualSalary'] = df['AnnualSalary'].fillna(df['AnnualSalary'].mean())

In [15]:
#Task 11- Replace the null values in Age with median of the values
df['Age'] = df['Age'].fillna(df['Age'].median())

In [16]:
#Task 12- Replace the null values in Gender with suitable measure of central tendency
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [17]:
#Task 13- Check for duplicates
print(df.duplicated().sum())

0

In [18]:
#Task 14 - Remove the duplicate record
df.drop_duplicates(inplace=True)
print(df.shape)

(776, 5)